name: handheld
options:
  bundleIdPrefix: com.fumiyakume
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "5.9"

targets:
  handheld:
    type: application
    platform: iOS
    sources:
      - Sources/handheld
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.fumiyakume.handheld
      INFOPLIST_GENERATION_MODE: GeneratedFile
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "現在地から目的地までの経路を表示するために使用します"

  handheldTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/handheldTests
    dependencies:
      - target: handheld
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.fumiyakume.handheldTests
      GENERATE_INFOPLIST_FILE: YES
